name: lint

on:
  push:
    branches: master
  pull_request:
    types: [opened, synchronize, reopened]

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Hatch
      run: pip install --upgrade hatch

    - name: Lint typing and code style
      run: hatch run lint:all
